### ISSUE TITLE
Crash with large files

### ISSUE THREAD

**Issue by Kitoko86** [lucasvr/demuxfs#2]
Hi,

Demuxfs crashes when you mount large MPEG ts file. In my case, it occurs with a full DVB-T multiplex recording that has a size of 5.9 GB. There are 8 GB of RAM memory on my computer running Ubuntu 20.04. If you want a file sample, I can provide it to test.

Regards.

**Comment by lucasvr** [comment]
I don't think I have ever tested it with files larger than 4GB. A sample file helps, for sure, as I don't have a capture device at hand.

**Comment by Kitoko86** [comment]
Is it a limitation of FUSE or is it linked to the implementation of the filesystem? I'm curious to know. Anyway, here is the [sample](https://drive.google.com/file/d/17eSt8fg__im_L5losEFLJNr21FpHEz7p/view?usp=sharing). 

Regards.

**Comment by lucasvr** [comment]
Thanks for the sample. I was able to reproduce the issue. I'll come back with a fix soon.

**Comment by lucasvr** [comment]
@Kitoko86, thanks for providing me access to the transport stream. This was an interesting one, as it features several malformed elements that were causing DemuxFS to access data beyond buffer limits and to make it crash in several ways. I've made the code more robust against such issues, although there are certainly more spots prone to such problems and that were not reviewed this time.

Please test the code again and let me know if it works for you now.

**Comment by Kitoko86** [comment]
@lucasvr , it works for me excepted that sometimes I have the same issue #3 as @artemies mentioned. Otherwise, I found something interesting about this transport stream with Wireshark. There should be other files sent by DSM-CC with the following names and extensions: webapp.tgz, programs.tgz and apps.tgz. Maybe I forgot some of them.

The generated content in DSM-CC repertory shows only one file called edito.tgz. Maybe the parsing code in Demuxfs missed the other ones. Just my 2 cents.

**Comment by lucasvr** [comment]
Thanks for letting me know that you also observe the errors from #3 with that transport stream. Let me close this one so we can monitor the progress of the new issue on #3.
